name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    container:
      image: ghcr.io/qwrx123/the-os-project-dockerimage:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ConfigureTests
        run: cmake -B build -DBUILD_TESTING=ON

      - name: Check formatting (tests config)
        run: cmake --build build --target format-check --parallel 4

      - name: Build Tests
        run: cmake --build build --config Release --parallel 4

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure

      - name: clean build
        run: rm -rf build

      - name: Configure Kernel
        run: cmake -B build 

      - name: Check formatting (kernel config)
        run: cmake --build build --target format-check --parallel 4

      - name: Build Kernel
        run: cmake --build build --config Release --parallel 4